apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ekscluster
  region: ap-south-1
nodeGroups:
   - name: nodegroup1
     desiredCapacity: 3
     instanceType: t2.micro
     ssh:
        publicKeyName: instancekey
